Revert "Add `compilation_context` to `SwiftInfo` (#815)"
This reverts commit 42036b5212fedcd0e1377100d34d7a83e79e7ed6.

```
Traceback (most recent call last):
File "/private/var/tmp/_bazel_ksmiley/c8513c989333be3c89713e16206869b2/external/build_bazel_rules_swift/swift/internal/swift_library.bzl", line 173, column 93, in _swift_library_impl
         module_context, cc_compilation_outputs, other_compilation_outputs = swift_common.compile(
File "/private/var/tmp/_bazel_ksmiley/c8513c989333be3c89713e16206869b2/external/build_bazel_rules_swift/swift/internal/compiling.bzl", line 1883, column 29, in compile
         run_toolchain_action(
File "/private/var/tmp/_bazel_ksmiley/c8513c989333be3c89713e16206869b2/external/build_bazel_rules_swift/swift/internal/actions.bzl", line 249, column 42, in run_toolchain_action
         action_inputs = _apply_action_configs(
File "/private/var/tmp/_bazel_ksmiley/c8513c989333be3c89713e16206869b2/external/build_bazel_rules_swift/swift/internal/actions.bzl", line 136, column 52, in _apply_action_configs
         action_inputs = _apply_configurator(
File "/private/var/tmp/_bazel_ksmiley/c8513c989333be3c89713e16206869b2/external/build_bazel_rules_swift/swift/internal/actions.bzl", line 67, column 28, in _apply_configurator
         return configurator(prerequisites, args)
File "/private/var/tmp/_bazel_ksmiley/c8513c989333be3c89713e16206869b2/external/build_bazel_rules_swift/swift/internal/compiling.bzl", line 1425, column 31, in _dependencies_swiftmodules_vfsoverlay_configurator
         inputs = swiftmodules + [prerequisites.vfsoverlay_file],
Error: unsupported binary operation: tuple + list
```