Add `always_include_developer_search_paths` to `mixed_language_library` (#1539)
This allows Swift code in the library to depend on XCTest.

If this was passed in `kwargs`, it gets passed along to the internal
`objc_library` targets:
```
~/Development/rules_swift master $ bazel build //examples/apple/mixed_language:MixedAnswer
ERROR: /Users/jschear/Development/rules_swift/examples/apple/mixed_language/BUILD:5:23: //examples/apple/mixed_language:MixedAnswer_headers: no such attribute 'always_include_developer_search_paths' in 'objc_library' rule
ERROR: /Users/jschear/Development/rules_swift/examples/apple/mixed_language/BUILD:5:23: //examples/apple/mixed_language:MixedAnswer_clang: no such attribute 'always_include_developer_search_paths' in 'objc_library' rule
```
We _could_ alternatively `.pop` it off of `kwargs` before passing to
`objc_library`, but tracking which attributes belong to `swift_library`
vs. `obj_library` and which are shared can get a bit complex.