Fix missing dependency (#865)
Fixes the following compilation error:
```
external/com_github_apple_swift_nio_transport_services/Sources/NIOTransportServices/NIOTSConnectionChannel.swift:20:8: error: no such module 'NIOTLS'
```