Add target label to layering check violation message (#1893)
Previously the layering check violation would only report the Swift
module name that is not directly declared as a dependency.
Now we make sure that target label is captured and displayed to the user
so that it is easier to act upon it.

Previously:

```shell
error: Layering violation in @@//test/fixtures/layering_check:layering_violation
The following modules were imported, but they are not direct dependencies of the target:

    TransitiveDependency

Please add the correct 'deps' to @@//test/fixtures/layering_check:layering_violation to import those modules.
```

now:

```shell
error: Layering violation in @@//test/fixtures/layering_check:layering_violation
The following modules were imported, but they are not direct dependencies of the target:

    TransitiveDependency (@@//test/fixtures/layering_check:TransitiveDependency)

Please add the correct 'deps' to @@//test/fixtures/layering_check:layering_violation to import those modules.
```

Users can now add the dependency way quicker and there could even be an
automated way to add the missing dep since the label is present.