Revert "Remove the `swift.no_generated_module_map` feature" (#1530)
This reverts commit 68b58f7a44026fcaa174de0f8dc678d753aadeb6. 

While we have a custom `mixed_language_library` rule that doesnt match
`upstream` we must maintain this feature or we get duplicate module
declaration errors as the mixed language rules depend on this feature
when they create their own modulemap

Without this commit reverted we get:

```sh
bazel-out/ios_sim_arm64-dbg-ios-sim_arm64-min16.0-applebin_ios-ST-2491983d010b/bin/Code/CoreLibraries/Contacts/Aliases/AliasesLegacy/AliasesLegacy.lib_swift_modulemap/_/module.modulemap:1:8: error: redefinition of module 'AliasesLegacy'
    1 | module "AliasesLegacy" {
      |        ^
bazel-out/ios_sim_arm64-dbg-ios-sim_arm64-min16.0-applebin_ios-ST-2491983d010b/bin/Code/CoreLibraries/Contacts/Aliases/AliasesLegacy/AliasesLegacy.lib/AliasesLegacy/module.modulemap:1:8: note: previously defined here
    1 | module "AliasesLegacy" {
      |        ^
1 error generated.
```

Part of: https://github.com/bazelbuild/rules_apple/pull/2729, we can
remove this feature when we upstream the mixed language support in
upstream.